export const images = {
  avatar: require('./avatar.png'),
  arrowLeft: require('./arrowLeft.png'),
  arrow_down: require('./arrow_down.png'),
  arrow_up: require('./arrow_up.png'),
  arrow_right: require('./arrow_right.png'),
  banner: require('./banner.png'),
  fina_splash: require('./splash.png'),
  fina_logo: require('./finaLogo.png'),
  headerDecor: require('./headerDecor.png'),
  close_eye: require('./close_eye.png'),
  fifth: require('./fitth.png'),
  bank: require('./bank.png'),
  insurance: require('./insurance.png'),
  invest: require('./invest.png'),
  house: require('./house.png'),
  car: require('./car.png'),
  coin: require('./coin.png'),
  cube: require('./box.png'),
  chart: require('./chart.png'),
  clock: require('./clock.png'),
  icon_x: require('./blue_x.png'),
  shield: require('./shield.png'),
  plane: require('./plane.png'),
  tool: require('./tool.png'),
  crash: require('./crash.png'),
}
