export const images = {
  common_right_arrow: require('./commons/right-arrow.png'),
  common_left_arrow: require('./commons/left-arrow.png'),
  common_copy: require('./commons/copy.png'),
  common_share_arrow: require('./commons/share-arrow.png'),
  common_share: require('./commons/share.png'),
  common_share_blue: require('./commons/share-blue.png'),
  common_fina_pay: require('./commons/fina-pay.png'),
  common_circle_checked: require('./commons/circle-checked.png'),
  common_upload: require('./commons/upload.png'),

  app_home: require('./bottom-bar/home.png'),
  app_chat: require('./bottom-bar/chat.png'),
  app_request: require('./bottom-bar/plus.png'),
  app_manage: require('./bottom-bar/manage.png'),
  app_profile: require('./bottom-bar/user.png'),

  invest_front: require('./invest/front.png'),
  invest_back: require('./invest/back.png'),
  invest_portrait: require('./invest/portrait.png'),

  commission_checked: require('./commission/checked.png'),
  commission_unchecked: require('./commission/unchecked.png'),
  commission_paid: require('./commission/paid.png'),
  commission_cancel: require('./commission/cancel.png'),
  commission_empty: require('./commission/empty.png'),

  identity_hidden : require('./identity/no-hidden.png'),
  identity_too_dark : require('./identity/no-too-dark.png'),
  identity_too_light : require('./identity/no-too-light.png'),
  vinacapital : require('./invest/vinacapital.png'),

  bonds_background : require('./invest/bonds-background.png'),
  home_arrow_up: require('./home/arrow-up.png'),
  home_finance: require('./home/home-finance.png'),
  financeHeader: require('./home/finance.png'),
  insuranceHeader: require('./home/insurance.png'),
  investHeader: require('./home/invest.png'),
  home_house: require('./home/house.png'),
  home_car: require('./home/car.png'),
  home_consumer: require('./home/shopping.png'),
  home_fix: require('./home/fixing.png'),
  home_ability_to_borrow: require('./home/ability_to_borrow.png'),
  home_real_estate: require('./home/real_estate.png'),
  home_introduce_borrowers: require('./home/introduce_borrowers.png'),
  home_records: require('./home/record_management.png'),
  home_notarial: require('./home/notarial_records.png'),
  home_planning_check: require('./home/planning_check.png'),
  home_calculate_tool: require('./home/calculate_tool.png'),
  home_hotSell: require('./home/hot.png'),
  home_health: require('./home/health.png'),
  home_thieves: require('./home/thieves.png'),
  home_rentHome: require('./home/rent-home.png'),
  home_realEstate: require('./home/real-estate.png'),
  home_tax: require('./home/tax.png'),
  home_budget: require('./home/budget.png'),

  profile_fina_icon: require('./profile/fina-icon.png'),
  profile_background: require('./profile/background.png'),
  profile_community: require('./profile/community.png'),
  profile_social: require('./profile/social-network.png'),
  profile_password: require('./profile/password.png'),
  profile_pin: require('./profile/pin.png'),
  profile_bank: require('./profile/bank.png'),
  profile_commission: require('./profile/commission.png'),
  profile_file: require('./profile/file.png'),
  profile_hotline: require('./profile/hotline.png'),
  profile_agent: require('./profile/agent.png'),
  profile_update_referral: require('./profile/referral-update.png'),
  profile_my_agent: require('./profile/my-agent.png'),
  profile_guide: require('./profile/guide.png'),
  profile_policy: require('./profile/policy.png'),
  profile_org: require('./profile/org.png'),
  profile_question: require('./profile/question.png'),
  profile_delete: require('./profile/delete-account.png'),
  profile_avatar_background: require('./profile/avatar-background.png'),
  profile_camera_icon: require('./profile/camera-icon.png'),
  profile_referral_background: require('./profile/referral-background.png'),

  statistical: require('./utilities/statistical.png'),
  management_finance: require('./management/finance.png'),
  management_insurance: require('./management/insurance.png'),
  management_invest: require('./management/invest.png'),
  invest_background: require('./invest/invest-background.png'),
  invest_home: require('./invest/invest-home.png'),
  swap: require('./invest/swap.png'),
  yellow_caution: require('./invest/caution.png'),

  insurance_extension: require('./utilities/insurance_extension.png'),
  claim: require('./utilities/claim.jpg'),
  hospital: require('./utilities/hospital.png'),
  support_channel: require('./utilities/support_channel.png'),
  insurance_handbook: require('./utilities/insurance_handbook.jpg'),
  avatar: require('./home/avatar.png'),
  arrowLeft: require('./arrowLeft.png'),
  arrow_down: require('./arrow_down.png'),
  arrow_up: require('./arrow_up.png'),
  arrow_right: require('./arrow_right.png'),
  long_arrow_right: require('./long-arrow-right.png'),
  banner: require('./banner.png'),
  fina_splash: require('./splash.png'),
  fina_logo: require('./finaLogo.png'),
  headerDecor: require('./headerDecor.png'),
  close_eye: require('./close_eye.png'),
  circle_x: require('./circle_x.png'),
  circle_tick: require('./circle_tick.png'),
  circle_clock: require('./circle_clock.png'),
  open_eye: require('./open_eye.png'),
  fifth: require('./fitth.png'),
  bank: require('./bank.png'),
  insurance: require('./insurance.png'),
  invest: require('./invest.png'),
  house: require('./house.png'),
  car: require('./car.png'),
  coin: require('./coin.png'),
  cube: require('./box.png'),
  chart: require('./chart.png'),
  clock: require('./clock.png'),
  icon_x: require('./blue_x.png'),
  shield: require('./shield.png'),
  plane: require('./plane.png'),
  tool: require('./tool.png'),
  crash: require('./crash.png'),
  phoneCalling: require('./phone-calling.png'),
  numberKeyboard: require('./number-keyboard.png'),
  clipboard: require('./clipboard-text.png'),
  ribbon: require('./ribbon.png'),
  caution: require('./caution.png'),
  first_aid: require('./first_aid.png'),
  shield_star: require('./shield_star.png'),
  dollar_coin: require('./dollar_coin.png'),
  note: require('./note.png'),
  wallet: require('./wallet.png'),
  check: require('./check.png'),
  defaultBackground: require('./defaultBackground.png'),
  insurance_detail: require('./insurance_detail.png'),
  id_front: require('./id_front.png'),
  id_back: require('./id_back.png'),
  id_deviate: require('./id_deviate.png'),
  id_too_dark: require('./id_too_dark.png'),
  id_too_light: require('./id_too_light.png'),
  insurance_default: require('./insurance-default.png'),
  defaultUpload: require('./default-upload.png'),
  avatarDefault: require('./avatar-default.png'),
}
