export enum ScreenNames {
  SPLASH = 'splash',
  AUTH = "Auth",
  APP = "App",
  LOGIN = "Login",
  REGISTER = "Register",
  REGISTER_PHONE = "RegisterPhone",
  NOTICE = "Notice",
  WELCOME = "Welcome",
  HOME = "Home",
  OTP = "Otp",
  SETTING = "Setting",
  CHAT = "Chat",
  SCHEDULE = "Schedule",
  PLUS = "Plus",
  REQUEST_COUNSELLING = "RequestCounselling",
  FORGOT_PASSWORD = "ForgotPassword",
  CHANGE_PASSWORD = "ChangePassword",
  LOAN_DETAIL = "LoanDetail",
  REGISTER_LOAN = "RegisterLoan",
  PROFILE_DETAIL = "ProfileDetail",
  FINANCE = 'Finance',
  TERM_AND_POLICY = 'TermAndPolicy',
  INSURANCE_SCREEN = 'InsuranceScreen',
  INSURANCE_DETAIL = 'InsuranceDetail',
  INSURANCE_PACKAGE = 'InsurancePackage'
}
